[supabase]
url = "https://gamonuqizjdfjmletvzo.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhbW9udXFpempkZmptbGV0dnpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1Njk5MDgsImV4cCI6MjA4MTE0NTkwOH0.UsxrmI8YsvimjCytyom0Vv819Ctajpr9GXD-LSU9WNw"